#!/bin/bash

name=$"Rolagem do mouse invertida"

if [[ $DESKTOP_SESSION == *plasma* ]]; then
    if [ "$(LANG=C kreadconfig5  --group "Mouse" --key "XLbInptNaturalScroll" --file "$HOME/.config/kcminputrc")" = "true" ]; then
        checked="checked"
    else
        checked=""
    fi
else
    checked=disabled
fi

# Use files from /usr/share/bigbashview/bcc/shell/ to show html, all functions from shel folder imported in index.sh.htm
showHtml () {
    eval "$defaultConfigSwitch switch"
}


