#!/bin/bash

name=$"Ativar o NumLock ao ligar o sistema"

if [[ $DESKTOP_SESSION == *plasma* ]]; then
     if LANG=C grep -q Numlock=on /etc/sddm.conf; then
        checked="checked"
    else
        checked=""
    fi
else
    checked=disabled
fi

# Use files from /usr/share/bigbashview/bcc/shell/ to show html, all functions from shel folder imported in index.sh.htm
showHtml () {
    eval "$defaultConfigSwitch run=\"$sectionFolder/$id/script.sh.htm\" switch"
}
