#!/bin/bash

name=$"Bloquear a edição da área de trabalho"

if [[ $DESKTOP_SESSION == *plasma* ]]; then
     if [ -e "$HOME/.config/lockplasma" ]; then
        checked="checked"
    else
        checked=""
    fi
else
    checked=disabled
fi

# Use files from /usr/share/bigbashview/bcc/shell/ to show html, all functions from shel folder imported in index.sh.htm
showHtml () {
    eval "$defaultConfigSwitch switch"
}
